# Generated by Django 6.0.3 on 2026-03-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
    ]
