# Generated by Django 6.0.3 on 2026-04-05 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_comment_options_book_valid_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.TextField(choices=[('fiction', 'Fiction'), ('romance', 'Romance'), ('non-fiction', 'Non-fiction'), ('fantasy', 'Fantasy'), ('sci-fi', 'Sci-Fi'), ('historical', 'Historical'), ('mystery', 'Mystery'), ('biography', 'Biography'), ('philosophy', 'Philosophy'), ('poetry', 'Poetry'), ('horror', 'Horror'), ('adventure', 'Adventure'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=2000),
        ),
        migrations.CreateModel(
            name='BookClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('current_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.book')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_clubs', to='main.profile')),
                ('members', models.ManyToManyField(blank=True, related_name='members', to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('wishlist', 'Want to Read'), ('Both', 'Both the book💸📖'), ('reading', 'Reading🧐'), ('finished', 'Finished🥳')], default='wishlist', max_length=40)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
            ],
            options={
                'unique_together': {('profile', 'book')},
            },
        ),
    ]
